### ISSUE TITLE
vue ui 后台运行安装插件的时候，报错TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by forrestlmj** [forrestlmj/vue_shop#5]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:36:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:36:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:36:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:36:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:36:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:39:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:39:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:39:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
    at Object.readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/folders.js:109:24)
    at readPackage (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:78:20)
    at getLink (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:170:15)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:58:16
    at Array.map (<anonymous>)
    at findDependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:53:5)
    at Object.list (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/connectors/dependencies.js:39:5)
    at dependencies (/usr/local/lib/node_modules/@vue/cli/node_modules/_@vue_cli-ui@4.3.1@@vue/cli-ui/apollo-server/schema/dependency.js:56:57) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ENOENT
npm ERR! syscall access
npm ERR! path /home/yangck/VsCodeWorkSpace/vue_shop/node_modules/@babel/helper-plugin-utils
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, access '/home/yangck/VsCodeWorkSpace/vue_shop/node_modules/@babel/helper-plugin-utils'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yangck/.npm/_logs/2020-05-14T21_52_55_585Z-debug.log
command failed: npm install --loglevel error @vue/cli-plugin-eslint
^A^A^C

**Comment by forrestlmj** [comment]
没什么很好的解决办法，就是删除node_models然后删除package.json.lock解决。然后重新运行npm install
